// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Infrastructure.Data;

#nullable disable

namespace TodoApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("TodoApp.Core.DataModel.TodoItemModel", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("_completed_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("_isCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("_submitted_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("_tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
